### ISSUE TITLE
Standard-Label bei "Task" Issue bitte auf "task" anstelle auf "feature" setzen.

### ISSUE THREAD

**Issue by specka** [zalf-rdm/.github#1]
**What is the task about | Worum geht es bei dieser Aufgabe**
Ich finde das neue Task-Template gut. Allerdings irritiert mich, dass hier bei Labels automatisch "feature" ausgewählt ist. Ich nehme dafür immer das Label "task", was inhaltlich besser passt. Bitte anpassen.

**Which steps are on the way to solve this task | Welche Schritte müssen für diese Aufgabe erledigt werden**

**Comment by mwallschlaeger** [comment]
done 

https://github.com/zalf-rdm/.github/blob/main/.github/ISSUE_TEMPLATE/task.md  can be edited directly in github.com
